using System.IO;

namespace CommentAdder
{
    class Program
    {
        static void Main(string[] args)
        {
            Go(args[0]);
        }

        private static void Go(string dir)
        {
            foreach (var subDir in Directory.GetDirectories(dir))
            {
                foreach (var f in Directory.GetFiles(subDir))
                {
                    if (f.EndsWith(".cs"))
                    {
                        AddComment(f);
                    }
                }

                Go(subDir);
            }
        }

        private static void AddComment(string filename)
        {
            string contents;

            using (var sr = new StreamReader(filename))
            {
                contents = sr.ReadToEnd();
                sr.Close();
            }
            
            using (var writer = new StreamWriter(filename))
            {
                writer.WriteLine("// <auto-generated />");
                writer.Write(contents);
                writer.Close();
            }
        }
    }
}
